serotypes: ['all', 'denv1', 'denv2', 'denv3', 'denv4']
genes: ['genome', 'E']

inputs:
  - name: ncbi
    metadata: "../ingest/results/metadata_{serotype}.tsv"
    sequences: "../ingest/results/sequences_{serotype}.fasta"

additional_inputs:
  - name: florida
    metadata: "../local/results/metadata_{serotype}.tsv"
    sequences: "../local/results/sequences_{serotype}.fasta"

filter:
  exclude: "defaults/exclude.txt"
  include:
    - "defaults/{serotype}/include.txt"
    - "../local/results/include_{serotype}.txt"
  group_by: "year region"
  min_length:
    genome: 5000
    E: 1000
  subsample_max_sequences: '4000'
  subsample_seed: '20260917'

traits:
  sampling_bias_correction: '3'
  traits_columns:
    all: 'region region_exposure serotype_genbank'
    denv1: 'country region country_exposure region_exposure serotype_genbank'
    denv2: 'country region country_exposure region_exposure serotype_genbank'
    denv3: 'country region country_exposure region_exposure serotype_genbank'
    denv4: 'country region country_exposure region_exposure serotype_genbank'

export:
  description: "defaults/description.md"
  title: "Dengue virus in Florida"
  maintainers:
    - name: "Florida Bureau of Public Health Laboratories"
  build_url: "https://github.com/BPHL-Molecular/nextstrain_dengue"
